// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ifood.Infrastructure.Data;

#nullable disable

namespace ifood.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ifood.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorHex = "#2ecc71",
                            Icone = "cash-stack",
                            Nome = "Salário",
                            Tipo = "Receita"
                        },
                        new
                        {
                            Id = 2,
                            CorHex = "#9b59b6",
                            Icone = "graph-up-arrow",
                            Nome = "Investimentos",
                            Tipo = "Receita"
                        },
                        new
                        {
                            Id = 3,
                            CorHex = "#1abc9c",
                            Icone = "plus-circle",
                            Nome = "Outras Receitas",
                            Tipo = "Receita"
                        },
                        new
                        {
                            Id = 4,
                            CorHex = "#e67e22",
                            Icone = "egg-fried",
                            Nome = "Alimentação",
                            Tipo = "Despesa"
                        },
                        new
                        {
                            Id = 5,
                            CorHex = "#3498db",
                            Icone = "car-front",
                            Nome = "Transporte",
                            Tipo = "Despesa"
                        },
                        new
                        {
                            Id = 6,
                            CorHex = "#e74c3c",
                            Icone = "house",
                            Nome = "Moradia",
                            Tipo = "Despesa"
                        },
                        new
                        {
                            Id = 7,
                            CorHex = "#f1c40f",
                            Icone = "controller",
                            Nome = "Lazer",
                            Tipo = "Despesa"
                        },
                        new
                        {
                            Id = 8,
                            CorHex = "#e84393",
                            Icone = "heart-pulse",
                            Nome = "Saúde",
                            Tipo = "Despesa"
                        },
                        new
                        {
                            Id = 9,
                            CorHex = "#16a085",
                            Icone = "book",
                            Nome = "Educação",
                            Tipo = "Despesa"
                        },
                        new
                        {
                            Id = 10,
                            CorHex = "#95a5a6",
                            Icone = "three-dots",
                            Nome = "Outros Gastos",
                            Tipo = "Despesa"
                        });
                });

            modelBuilder.Entity("ifood.Domain.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("ifood.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ifood.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("ifood.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Categorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ifood.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("ifood.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Transacoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ifood.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Transacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ifood.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("ifood.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
